@endpoint = https://qyzda2rb8h.execute-api.eu-west-3.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces/
###

GET {{endpoint}}/spaces?spaceId=3b4373aa-b4ab-431c-8c25-8748d87f9e8c
###

PUT {{endpoint}}/spaces?spaceId=3b4373aa-b4ab-431c-8c25-8748d87f9e8c
Content-Type: application/json

{
    "location": "Vienna",
    "name": "Vienna better than London",
    "updated": "true"
}
###

GET {{endpoint}}/spaces?location=Vienna
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Kharkiv",
    "name": "location"
}
###