@endpoint = https://qyzda2rb8h.execute-api.eu-west-3.amazonaws.com/prod/

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces/
###

GET {{endpoint}}/spaces?spaceId=3b4373aa-b4ab-431c-8c25-8748d87f9e8c
###
GET {{endpoint}}/spaces?location=Vienna
###

PUT {{endpoint}}/spaces?spaceId=ae2eb0ea-e9a8-4fbc-8c73-8d9616bae186
Content-Type: application/json

{
    "location": "Vienna",
    "name": "Vienna better than London",
    "updated": "true"
}
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Lviv",
    "name": "location"
}
###

DELETE {{endpoint}}/spaces/?spaceId=a3c986d7-1615-4599-a3e4-58324b8130a9